import numpy as np

## arange

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
 np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [13]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [14]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [15]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [17]:
np.random.randn(8)

array([-0.91617493, -0.80148407,  0.83929904,  0.05890064,  0.49415599,
        0.2264439 , -0.92936673,  0.08042452])

In [18]:
np.random.randn(4,4)

array([[ 0.65309668,  0.24920532,  1.78545496,  1.32663395],
       [ 0.16444703,  1.45415788, -0.37841682,  0.92482585],
       [ 0.26688183,  0.39758742,  0.01825251,  0.60594584],
       [-0.12174219,  1.22911693,  1.30117313, -0.06309526]])

In [19]:
np.random.randint(1,10)

5

In [20]:
np.random.randint(1,10,3)

array([3, 3, 4])

In [21]:
 benimNumpyDizim = np.arange(30)

In [22]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
benimRandomDizim = np.random.randint(0,100,30)

In [24]:
benimRandomDizim

array([55, 86, 72,  9, 70, 24,  3, 88, 80, 85, 94, 29,  6, 59, 55, 39, 98,
       16, 26, 54, 39, 20, 79, 64, 31, 16,  5,  4, 25, 43])

## numpy dizi methodları

In [25]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
benimNumpyDizim.max()

29

In [32]:
benimRandomDizim.max()

98

In [33]:
benimRandomDizim.min()

3

In [34]:
benimRandomDizim.argmax()

16

In [35]:
benimNumpyDizim.shape

(30,)

In [36]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [38]:
reshapeDizim.shape

(5, 6)